'use strict';
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={loss:'Функция не найдена',duplicate:'Возможное дублирование',conflict:'Потенциальный конфликт',change:'Изменение',missing:'Не найдена',preserved:'Сохранена',modified:'Изменена',moved:'Перенесена',created:'Создано',new:'Создано',added:'Создано',removed:'Не найдено после',retained:'Сохранено',unchanged:'Сохранено',reorganized:'Преобразовано',transformed:'Преобразовано',renamed:'Переименовано',pending:'На проверке',confirmed:'Подтверждено',rejected:'Отклонено',high:'Высокий',medium:'Средний',low:'Низкий'};
const colors={loss:'red',duplicate:'amber',conflict:'amber',change:'blue',missing:'red',preserved:'teal',modified:'blue',moved:'teal',created:'teal',new:'teal',added:'teal',removed:'red',high:'red',medium:'amber',low:'blue',confirmed:'teal',rejected:'blue'};
const icons={loss:'−',duplicate:'⧉',conflict:'!',change:'↗'};
let state={before:[],after:[],analysis:null,view:'overview',filter:'all',decisions:{},notes:{},busy:false,label:'',health:{},importWarnings:[]};
function tag(text,color=''){return '<span class="tag '+color+'">'+esc(text)+'</span>'}
function msg(text,error=false,busy=false){$('#global-message').innerHTML=text?'<div class="message '+(error?'error':'')+'">'+esc(text)+(busy?'<div class="loading-line"></div>':'')+'</div>':''}
async function api(path,body){const res=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await res.json();if(!res.ok)throw Error(data.error||'Ошибка запроса');return data}
function setBusy(b){state.busy=b;$('#run-analysis').disabled=b;$('#load-demo').disabled=b;$$('input[type=file]').forEach(el=>el.disabled=b);$('#new-analysis').disabled=b;$$('[data-owner-side]').forEach(el=>el.disabled=b)}
function setView(view){state.view=view;$$('.view').forEach(el=>el.classList.toggle('hidden',el.id!=='view-'+view));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));const names={upload:['Комплекты документов','Начните с двух версий.','Добавьте документы до и после организационных изменений.'],overview:['Результаты','Каждая функция на своём месте.','Изменения ответственности с подтверждением в исходных документах.'],mapping:['Карта функций','Что сохранилось. Что изменилось.','Проследите путь каждой функции между редакциями.'],report:['Заключение','От анализа — к решению.','Проверяемое заключение для согласования организационных изменений.']};$('#page-label').textContent=names[view][0];$('#page-title').textContent=names[view][1];$('#page-subtitle').textContent=names[view][2];if(view==='report')renderReport();if(view==='mapping')renderMapping()}
function renderFiles(){document.querySelector('#import-warnings').innerHTML=(state.importWarnings||[]).map(w=>'<div class='+String.fromCharCode(34)+'warning'+String.fromCharCode(34)+'>'+esc(w)+'</div>').join('');for(const side of ['before','after']){$('#list-'+side).innerHTML=state[side].map((d,i)=>'<div class="file-row"><span>▤</span><div><strong>'+esc(d.name)+'</strong><small>'+d.text.length.toLocaleString('ru')+' символов'+(d.warnings?.length?' · есть предупреждения':'')+'</small><input aria-label="Подразделение для '+esc(d.name)+'" placeholder="Подразделение — необязательно" value="'+esc(d.unit||'')+'" data-owner-side="'+side+'" data-index="'+i+'">'+(d.warnings||[]).map(w=>'<div class="warning">'+esc(w)+'</div>').join('')+'</div><button class="icon-button" aria-label="Удалить '+esc(d.name)+'" data-remove-side="'+side+'" data-index="'+i+'">×</button></div>').join('')}}
async function loadDemo(run=false){if(state.busy)return;setBusy(true);msg('Загружаем комплект…',false,true);try{const d=await api('/api/demo?case='+$('#demo-choice').value);state.before=d.before;state.after=d.after;state.label=d.label;state.importWarnings=[];state.analysis=null;state.decisions={};state.notes={};renderFiles();renderAll();msg('Комплект загружен. Можно запустить сравнение.');}catch(e){msg(e.message,true)}finally{setBusy(false)}if(run&&state.before.length&&state.after.length)await runAnalysis()}
async function readFiles(side,files){if(state.busy)return;const entries=Array.from(files);if(!entries.length)return;setBusy(true);msg('Извлекаем текст из документов…',false,true);try{const payload=[];for(const file of entries){if(file.size>15*1024*1024)throw Error(file.name+': превышен лимит 15 МБ');const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});payload.push({name:file.name,content})}const result=await api('/api/extract',{files:payload});const errors=[];for(const d of result.files){if(d.error||!d.text?.trim())errors.push(d.name+': '+(d.error||'читаемый текст отсутствует'));else state[side].push(d)}state.importWarnings.push(...errors.map(x=>'Не обработан файл: '+x));state.label='Пользовательский комплект';state.analysis=null;renderFiles();renderAll();msg(errors.length?'Добавлены читаемые документы. Ошибки: '+errors.join('; '):'Документы добавлены. Комплект готов к сравнению.',Boolean(errors.length))}catch(e){msg(e.message,true)}finally{setBusy(false);$('#files-'+side).value=''}}
async function runAnalysis(){if(state.busy)return;if(!state.before.length||!state.after.length){msg('Добавьте хотя бы один документ в каждый комплект.',true);setView('upload');return}setBusy(true);msg('Извлекаем пункты, сопоставляем ответственность и проверяем источники…',false,true);try{state.analysis=await api('/api/analyze',{before:state.before,after:state.after,llm:$('#use-llm').checked});state.analysis.warnings.push(...state.importWarnings);state.decisions={};state.notes={};state.filter='all';$('#severity-filter').value='all';$$('[data-filter]').forEach(el=>el.classList.toggle('active',el.dataset.filter==='all'));renderAll();setView('overview');msg('Анализ завершён за '+(state.analysis.elapsedMs/1000).toLocaleString('ru',{maximumFractionDigits:2})+' с. Проверьте замечания и сформируйте заключение.')}catch(e){msg(e.message,true)}finally{setBusy(false)}}
function findings(){return state.analysis?.findings||[]}
function references(x){return (x?.evidence||[]).map(e=>typeof e==='string'?(state.analysis?.documents||[]).flatMap(d=>d.clauses||[]).find(c=>c.id===e):e).filter(Boolean)}
function refLabel(e){return (e.document||e.name||'Документ')+' · п. '+(e.ref||'фрагмент')}
function renderAll(){renderOverview();renderMapping();renderReport();$('#export-top').disabled=!state.analysis;$('#nav-count').textContent=state.analysis?findings().length:''}
function renderOverview(){const a=state.analysis;if(!a){$('#dataset-banner').innerHTML='<div class="panel empty"><strong>Загрузите комплект для сравнения</strong>Используйте реальные редакции или контрольный пример на вкладке «Комплекты документов».</div>';$('#stats').innerHTML='';$('#findings-list').innerHTML='<div class="empty">Здесь появятся замечания с источниками</div>';$('#units-list').innerHTML='';$('#trace-list').innerHTML='';$('#warnings').innerHTML='';$('#engine-label').innerHTML='';$('#finding-total').textContent='';return}
 const docs=a.documents||[];const nBefore=docs.filter(d=>d.side==='before').length||state.before.length,nAfter=docs.filter(d=>d.side==='after').length||state.after.length;const clauses=docs.reduce((n,d)=>n+(d.clauses?.length||0),0);
 $('#dataset-banner').innerHTML='<div class="dataset-icon">▤</div><div><small>ИСХОДНЫЙ КОМПЛЕКТ</small><strong>'+nBefore+' документ'+(nBefore===1?'':'а')+' · до</strong></div><div class="dataset-arrow">→</div><div><small>НОВЫЙ КОМПЛЕКТ</small><strong>'+nAfter+' документ'+(nAfter===1?'':'а')+' · после</strong></div><div class="dataset-meta"><b>'+esc(state.label)+'</b><br>'+clauses+' извлечённых фрагментов · '+(a.elapsedMs/1000).toLocaleString('ru',{maximumFractionDigits:2})+' с</div>';
 const fs=findings(),m=a.mappings||[];const cards=[['Функции без соответствия',fs.filter(f=>f.type==='loss').length,'red','−','Кандидаты на проверку'],['Возможные дубли',fs.filter(f=>f.type==='duplicate').length,'amber','⧉','Сопоставление ответственности'],['Конфликты интересов',fs.filter(f=>f.type==='conflict').length,'amber','!','Проверка разделения ролей'],['Сопоставлено функций',m.filter(x=>x.after).length,'teal','↗','Из '+m.length+' исходных фрагментов']];
 $('#stats').innerHTML=cards.map(c=>'<div class="stat"><div class="stat-top">'+c[0]+'<span class="stat-symbol '+c[2]+'">'+c[3]+'</span></div><div class="stat-number">'+c[1]+'</div><div class="stat-note">'+c[4]+'</div></div>').join('');
 $('#finding-total').textContent=fs.length;renderFindings();
 const units=a.units||[];$('#unit-count').textContent=units.length+' подразделений';
 $('#units-list').innerHTML=units.length?units.map((u,i)=>'<div class="unit-card"><h3>'+esc(u.name)+'</h3>'+tag(labels[u.status]||u.status,colors[u.status]||'')+'<br><button data-unit="'+i+'">Открыть основание ↗</button></div>').join(''):'<div class="empty">Явные перечни подразделений не обнаружены. Уточните владельцев при загрузке.</div>';
 const trace=a.trace||[];$('#trace-list').innerHTML=trace.map(t=>'<div class="trace-step"><span class="trace-dot">'+(t.status==='error'?'!':'✓')+'</span><div><strong>'+esc(t.step)+'</strong><p>'+esc(t.detail||'')+'</p></div></div>').join('');
 const engine=a.engine||{};$('#engine-label').innerHTML='<b>'+esc(engine.name||'Локальный анализ')+'</b><br>'+esc(engine.llmUsed?'Языковая модель участвовала в проверке':'Лексическое сопоставление и экспертные правила. LLM не использовалась.')+'<br>Сходство текста не является вероятностью правильности вывода.';
 $('#warnings').innerHTML=(a.warnings||[]).map(w=>'<div class="warning">'+esc(w)+'</div>').join('')
}
function renderFindings(){const severity=$('#severity-filter').value;let fs=findings().filter(f=>(state.filter==='all'||f.type===state.filter)&&(severity==='all'||f.severity===severity));$('#findings-list').innerHTML=fs.length?fs.map(f=>'<button class="finding" data-finding="'+esc(f.id)+'"><span class="finding-icon '+(colors[f.type]||'blue')+'">'+(icons[f.type]||'↗')+'</span><span class="finding-content"><span class="finding-title">'+esc(f.title)+'</span><span class="finding-sub">'+esc(references(f).map(refLabel).join(' ↔ '))+'</span><span class="finding-meta">'+tag(labels[f.severity]||'Средний',colors[f.severity])+tag(labels[f.type],colors[f.type])+tag(labels[state.decisions[f.id]||'pending'],colors[state.decisions[f.id]])+'</span></span><span class="chevron">›</span></button>').join(''):'<div class="empty"><strong>Замечаний по этому фильтру нет</strong>Отсутствие замечаний не подтверждает полноту документов.</div>'}
function renderMapping(){renderFlows();const all=state.analysis?.mappings||[];const q=$('#mapping-search').value.toLowerCase();const status=$('#mapping-filter').value;const list=all.filter(m=>(status==='all'||m.status===status)&&JSON.stringify([m.before?.text,m.after?.text,m.before?.ref,m.after?.ref,m.before?.unit,m.after?.unit]).toLowerCase().includes(q));$('#mapping-count').textContent=list.length+' из '+all.length;$('#mapping-body').innerHTML=list.map(m=>'<tr><td><button data-mapping="'+esc(m.id)+'"><strong>п. '+esc(m.before?.ref)+' · '+esc(m.before?.unit||'Владелец не определён')+'</strong><p>'+esc(m.before?.text)+'</p><small>'+esc(m.before?.document)+'</small></button></td><td>'+(m.after?'<button data-mapping="'+esc(m.id)+'"><strong>п. '+esc(m.after.ref)+' · '+esc(m.after.unit||'Владелец не определён')+'</strong><p>'+esc(m.after.text)+'</p><small>'+esc(m.after.document)+'</small></button>':'<span class="muted">Соответствие не найдено в комплекте</span>')+'</td><td>'+tag(labels[m.status]||m.status,colors[m.status])+'</td><td>'+Math.round((Number(m.score)||0)*100)+'%<br><small>сходство</small></td></tr>').join('')||'<tr><td colspan="4" class="empty">Нет функций для отображения</td></tr>'}

function renderFlows(){
 const host=$('#flow-list');if(!host)return;
 const groups=new Map();
 for(const m of state.analysis?.mappings||[]){if(m.status!=='moved'||!m.after)continue;const key=m.before.unit+' → '+m.after.unit;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(m)}
 host.innerHTML=Array.from(groups.entries()).map(([key,items])=>'<button class="flow-row" data-mapping="'+esc(items[0].id)+'"><span>'+esc(items[0].before.unit)+'</span><span class="flow-arrow">→<small>'+items.length+' соответствий</small></span><span>'+esc(items[0].after.unit)+'</span></button>').join('')||'<p class="muted">Переносы между явно определёнными владельцами не найдены.</p>';
}

function quote(e){return '<section class="quote-card"><small>'+esc(e.side==='before'?'ДО ИЗМЕНЕНИЙ':'ПОСЛЕ ИЗМЕНЕНИЙ')+'</small><strong class="source-name">'+esc(e.document||e.name||'Документ')+'</strong>'+tag('Пункт '+(e.ref||'—'))+(e.unit?' '+tag(e.unit):'')+'<blockquote>'+esc(e.text)+'</blockquote>'+(e.line?'<small>Строка извлечённого текста: '+esc(e.line)+'</small>':'')+'</section>'}
function openEvidence(f){const evidence=references(f);const isFinding=findings().some(x=>x.id===f.id);$('#evidence-content').innerHTML='<div>'+tag(labels[f.type]||'Сопоставление',colors[f.type])+'</div><h2 id="evidence-title">'+esc(f.title)+'</h2><p>'+esc(f.explanation||f.reason||'')+'</p>'+(f.confidence?'<p class="muted">'+esc(typeof f.confidence==='number'?'Оценка правила: '+f.confidence:f.confidence)+'</p>':'')+'<div class="evidence-grid">'+evidence.map(quote).join('')+'</div>'+(f.recommendation?'<div class="recommendation"><strong>Рекомендация</strong>'+esc(f.recommendation)+'</div>':'')+(isFinding?'<textarea class="review-note" id="review-note" placeholder="Комментарий эксперта — необязательно" aria-label="Комментарий эксперта">'+esc(state.notes[f.id]||'')+'</textarea><div class="review-actions"><span>'+labels[state.decisions[f.id]||'pending']+'</span><button class="button secondary" data-decision="pending" data-id="'+esc(f.id)+'">Позже</button><button class="button secondary" data-decision="rejected" data-id="'+esc(f.id)+'">Отклонить</button><button class="button primary" data-decision="confirmed" data-id="'+esc(f.id)+'">Подтвердить</button></div>':'');$('#evidence-dialog').showModal()}
function reportBody(){const a=state.analysis;if(!a)return '<div class="empty">Сначала выполните анализ документов.</div>';const fs=findings(),confirmed=fs.filter(f=>state.decisions[f.id]==='confirmed').length,rejected=fs.filter(f=>state.decisions[f.id]==='rejected').length;return '<div class="eyebrow">ORGLENS / АНАЛИТИЧЕСКОЕ ЗАКЛЮЧЕНИЕ</div><h2>Анализ организационной структуры и функционала</h2><p>'+esc(state.label)+'</p><p>Дата анализа: '+esc(new Date(a.generatedAt||Date.now()).toLocaleString('ru-RU'))+'</p><h3>1. Основание и охват</h3><p>Сопоставлены '+state.before.length+' документ(ов) исходного комплекта и '+state.after.length+' документ(ов) новой редакции. Анализ выполнен за '+(a.elapsedMs/1000).toLocaleString('ru',{maximumFractionDigits:2})+' с.</p><ul>'+(a.documents||[]).map(d=>'<li>'+esc(d.side==='before'?'До: ':'После: ')+esc(d.name)+'</li>').join('')+'</ul><h3>2. Результат экспертной проверки</h3><p>Наблюдений: '+fs.length+'. Подтверждено: '+confirmed+'. Отклонено: '+rejected+'. Ожидают проверки: '+(fs.length-confirmed-rejected)+'. Подтверждение фиксируется пользователем и не является автоматическим заключением.</p><h3>3. Подразделения</h3><ul>'+(a.units||[]).map(u=>'<li>'+esc(u.name)+' — '+esc(labels[u.status]||u.status)+'</li>').join('')+'</ul><h3>4. Замечания и рекомендации</h3>'+fs.map((f,i)=>'<div class="report-item"><strong>'+String(i+1)+'. '+esc(f.title)+'</strong> '+tag(labels[state.decisions[f.id]||'pending'],colors[state.decisions[f.id]])+'<p>'+esc(f.explanation)+'</p><p><b>Рекомендация:</b> '+esc(f.recommendation)+'</p>'+(state.notes[f.id]?'<p><b>Комментарий эксперта:</b> '+esc(state.notes[f.id])+'</p>':'')+references(f).map(e=>'<p><b>'+esc(refLabel(e))+'</b><br>«'+esc(e.text)+'»</p>').join('')+'</div>').join('')+'<h3>5. Метод и ограничения</h3><p>'+esc(a.engine?.name||'Локальное сопоставление')+'. '+(a.engine?.llmUsed?'Использовалась дополнительная локальная языковая модель.':'Языковая модель не использовалась. Применены лексическое сопоставление и экспертные правила.')+' Числовая оценка сходства не является вероятностью корректности. Отсутствие соответствия означает отсутствие подтверждения в предоставленном комплекте. Проверка законодательства и внешних стандартов не выполнялась. Документы рассматриваются как данные, инструкции внутри документов не исполняются.</p>'+ (a.warnings||[]).map(w=>'<p>'+esc(w)+'</p>').join('')+'<p>Заключение носит рекомендательный характер. Требуется проверка ответственным сотрудником.</p>'}
function renderReport(){$('#report-preview').innerHTML=reportBody()}
async function download(name,content,type){try{const result=await api('/api/export',{content,extension:name.split('.').pop()});const a=document.createElement('a');a.href=result.href;a.download=name;document.body.appendChild(a);a.click();a.remove();msg('Файл сохранён локально: '+result.path);}catch(e){msg('Не удалось сохранить файл: '+e.message,true)}}
function exportHTML(){if(!state.analysis){setView('upload');return}const content='<!doctype html><html lang="ru"><meta charset="utf-8"><title>OrgLens — заключение</title><style>body{max-width:1000px;margin:50px auto;padding:0 30px;font:16px/1.7 Arial,sans-serif;color:#1b2b40}h2{font-size:29px}h3{margin-top:32px}.eyebrow{font-size:12px;color:#087f82;letter-spacing:1px}.tag{font-size:12px;border:1px solid #ccd7e0;padding:3px 7px;border-radius:4px}.report-item{border-bottom:1px solid #dde3e8;padding:18px 0}p{overflow-wrap:anywhere}@media print{body{margin:0;max-width:none}.report-item{break-inside:avoid}}</style><body>'+reportBody()+'</body></html>';download('OrgLens-заключение.html',content,'text/html;charset=utf-8')}
function exportCSV(){if(!state.analysis)return;const cell=v=>{let s=String(v??'');if(/^(\s*[=+@-]|[\t\r])/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const rows=[['Статус','Документ до','Пункт до','Владелец до','Функция до','Документ после','Пункт после','Владелец после','Функция после','Сходство']];for(const m of state.analysis.mappings||[])rows.push([labels[m.status],m.before?.document,m.before?.ref,m.before?.unit,m.before?.text,m.after?.document,m.after?.ref,m.after?.unit,m.after?.text,m.score]);download('OrgLens-функции.csv','\ufeff'+rows.map(row=>row.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8')}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const filter=e.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;$$('[data-filter]').forEach(el=>el.classList.toggle('active',el===filter));renderFindings()}const finding=e.target.closest('[data-finding]');if(finding){const f=findings().find(f=>f.id===finding.dataset.finding);if(f)openEvidence(f)}const mapping=e.target.closest('[data-mapping]');if(mapping){const m=state.analysis.mappings.find(m=>m.id===mapping.dataset.mapping);if(m)openEvidence({id:m.id,title:labels[m.status]+' · п. '+m.before.ref,reason:m.reason,evidence:[m.before,m.after].filter(Boolean)})}const unit=e.target.closest('[data-unit]');if(unit){const u=state.analysis.units[Number(unit.dataset.unit)];openEvidence({id:'unit',title:u.name,explanation:labels[u.status]||u.status,evidence:u.evidence||[]})}const decision=e.target.closest('[data-decision]');if(decision){state.decisions[decision.dataset.id]=decision.dataset.decision;state.notes[decision.dataset.id]=$('#review-note').value;$('#evidence-dialog').close();renderFindings();renderReport()}const remove=e.target.closest('[data-remove-side]');if(remove&&!state.busy){state[remove.dataset.removeSide].splice(Number(remove.dataset.index),1);state.analysis=null;renderFiles();renderAll()}});
document.addEventListener('input',e=>{if(e.target.dataset.ownerSide){state[e.target.dataset.ownerSide][Number(e.target.dataset.index)].unit=e.target.value;state.analysis=null;renderAll();msg('Владелец изменён. Повторите анализ, чтобы обновить результаты.')}});
$('#new-analysis').onclick=()=>setView('upload');$('#export-top').onclick=()=>{if(state.analysis)setView('report');else setView('upload')};
$('#close-dialog').onclick=()=>$('#evidence-dialog').close();$('#evidence-dialog').addEventListener('click',e=>{if(e.target===$('#evidence-dialog'))$('#evidence-dialog').close()});
$('#load-demo').onclick=()=>loadDemo(false);$('#run-analysis').onclick=runAnalysis;$('#severity-filter').onchange=renderFindings;$('#mapping-filter').onchange=renderMapping;$('#mapping-search').oninput=renderMapping;
$('#export-html').onclick=exportHTML;$('#export-csv').onclick=exportCSV;$('#export-json').onclick=()=>{if(state.analysis)download('OrgLens-анализ.json',JSON.stringify({...state.analysis,expertDecisions:state.decisions,expertNotes:state.notes},null,2),'application/json;charset=utf-8')};
for(const side of ['before','after']){$('#files-'+side).onchange=e=>readFiles(side,e.target.files);const dz=$('#drop-'+side);dz.ondragover=e=>{e.preventDefault();dz.classList.add('drag')};dz.ondragleave=()=>dz.classList.remove('drag');dz.ondrop=e=>{e.preventDefault();dz.classList.remove('drag');readFiles(side,e.dataTransfer.files)}}
(async()=>{try{state.health=await api('/api/health');$('#use-llm').disabled=!state.health.llmConfigured;$('#llm-help').textContent=state.health.llmConfigured?'Настроена модель '+state.health.llmModel+'. Текст передаётся локальному сервису Ollama.':'Локальная модель не настроена. Основной сценарий работает без ключей и интернета.';if(!state.health.pdf)$('#llm-help').textContent+=' Для PDF установите зависимости из requirements.txt.';await loadDemo(true)}catch(e){msg('Не удалось подключиться к локальному серверу: '+e.message,true);setView('upload')}})();
