'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusLabels={unchanged:'Без изменений',changed:'Изменён',added:'Добавлен',removed:'Удалён',moved:'Перенумерован / перенесён'};
const riskLabels={loss:'Кандидат потери',duplicate:'Возможное пересечение',conflict:'Потенциальный конфликт',change:'Изменение',pending:'На проверке',confirmed:'Подтверждено',rejected:'Отклонено'};
let state={before:[],after:[],analysis:null,view:'comparison',filter:'all',busy:false,label:'',warnings:[],health:{},decisions:{},notes:{}};
function message(text,error=false,busy=false){$('#message').innerHTML=text?'<div class="message '+(error?'error':'')+'">'+esc(text)+(busy?'<div class="loading-line"></div>':'')+'</div>':''}
async function api(url,body){const res=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await res.json();if(!res.ok)throw Error(data.error||'Не удалось выполнить запрос');return data}
function busy(value){state.busy=value;$('#run-analysis').disabled=value;$('#load-demo').disabled=value;$('#new-comparison').disabled=value;$$('input[type=file],[data-name-side],[data-owner-side],[data-remove-side]').forEach(el=>el.disabled=value);$('#export-table').disabled=value||!state.analysis}
function setView(view){state.view=view;$$('.view').forEach(el=>el.classList.toggle('hidden',el.id!=='view-'+view));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));const titles={comparison:['Сравнение документов','Каждый пункт по порядку. Каждое изменение — перед глазами.'],documents:['Выберите два документа','Загрузите исходную и новую редакции для постатейного сравнения.'],report:['Заключение по изменениям','Полная сравнительная таблица и замечания для экспертной проверки.']};$('#page-title').textContent=titles[view][0];$('#page-subtitle').textContent=titles[view][1];if(view==='report')renderReport()}
function invalidate(){state.analysis=null;state.decisions={};state.notes={};renderResults();message('Документы изменились. Выполните сравнение, чтобы обновить таблицу.')}
function renderFiles(){for(const side of ['before','after']){$('#list-'+side).innerHTML=state[side].map((d,i)=>'<div class="file-row"><span class="file-icon">▤</span><div><strong>'+esc(d.name)+'</strong><small>'+d.text.length.toLocaleString('ru')+' символов</small><input value="'+esc(d.name)+'" data-name-side="'+side+'" data-index="'+i+'" aria-label="Название документа '+(side==='before'?'1':'2')+' — файл '+(i+1)+'" placeholder="Название в заголовке таблицы"><input value="'+esc(d.unit||'')+'" data-owner-side="'+side+'" data-index="'+i+'" aria-label="Подразделение для файла '+(i+1)+'" placeholder="Подразделение — необязательно">'+(d.warnings||[]).map(w=>'<div class="warning">'+esc(w)+'</div>').join('')+'</div><button class="icon-button" data-remove-side="'+side+'" data-index="'+i+'" aria-label="Удалить '+esc(d.name)+'">×</button></div>').join('')}$('#import-warnings').innerHTML=state.warnings.map(w=>'<div class="warning">'+esc(w)+'</div>').join('')}
async function loadDemo(run=false){if(state.busy)return;busy(true);message('Загружаем документы…',false,true);try{const result=await api('/api/demo?case='+$('#demo-choice').value);state.before=result.before;state.after=result.after;state.label=result.label;state.warnings=[];state.analysis=null;renderFiles();renderResults();message('Документы загружены. Нажмите «Сравнить документы».')}catch(e){message(e.message,true)}finally{busy(false)}if(run&&state.before.length&&state.after.length)await analyze()}
async function readFiles(side,files){if(state.busy)return;const selected=Array.from(files);if(!selected.length)return;busy(true);message('Извлекаем текст из файлов…',false,true);try{const payload=[];for(const file of selected){if(file.size>15*1024*1024)throw Error(file.name+': файл больше 15 МБ');const content=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('Ошибка чтения '+file.name));r.readAsDataURL(file)});payload.push({name:file.name,content})}const data=await api('/api/extract',{files:payload});const errors=[];for(const d of data.files){if(d.error||!d.text?.trim())errors.push('Не обработан '+d.name+': '+(d.error||'нет текста'));else state[side].push(d)}state.warnings.push(...errors);state.label='Пользовательские документы';state.analysis=null;renderFiles();renderResults();message(errors.length?errors.join('; '):'Файлы добавлены. Можно сравнить документы.',Boolean(errors.length))}catch(e){message(e.message,true)}finally{busy(false);$('#files-'+side).value=''}}
async function analyze(){if(state.busy)return;if(!state.before.length||!state.after.length){message('Добавьте хотя бы один файл для документа 1 и документа 2.',true);setView('documents');return}busy(true);message('Сравниваем все пункты и выделяем изменения…',false,true);try{const data=await api('/api/analyze',{before:state.before,after:state.after,llm:$('#use-llm').checked});if(!data.comparison?.rows)throw Error('Сервер нужно перезапустить: модуль полного сравнения ещё не загружен.');state.analysis=data;state.analysis.warnings.push(...state.warnings);state.decisions={};state.notes={};state.filter='all';$('#search').value='';$('#status-filter').value='all';$$('[data-filter]').forEach(el=>el.classList.toggle('active',el.dataset.filter==='all'));renderResults();setView('comparison');message('Сравнение готово. Все пункты показаны по порядку, изменённые фрагменты выделены.');$('.comparison-scroll').scrollTop=0;}catch(e){message(e.message,true)}finally{busy(false)}}
function rows(){return state.analysis?.comparison?.rows||[]}
function names(side){return state.analysis?.comparison?.documents?.[side]?.map(d=>d.name)||state[side].map(d=>d.name)}
function docTitle(side){return names(side).join(' + ')||(side==='before'?'Исходная редакция':'Новая редакция')}
function partHTML(parts,fallback){if(!parts?.length)return esc(fallback);return parts.map(p=>p.kind==='removed'?'<del>'+esc(p.text)+'</del>':p.kind==='added'?'<ins>'+esc(p.text)+'</ins>':esc(p.text)).join('')}
function cellHTML(c,parts,side,row){if(!c)return '<div class="absence"><span>—</span>'+'Данный пункт в документе отсутствует.'+'</div>';const numberChanged=row.before&&row.after&&/^\d+(?:\.\d+)*(?:\.[а-яa-z])?$/.test(row.before.ref)&&/^\d+(?:\.\d+)*(?:\.[а-яa-z])?$/.test(row.after.ref)&&row.before.ref!==row.after.ref;return '<div class="clause-top"><span class="clause-ref '+(numberChanged?'diff-ref':'')+'">'+esc(c.ref||'Фрагмент')+'</span>'+(names(side).length>1?'<span class="source-label">'+esc(c.document)+'</span>':'')+'</div><div class="doc-text">'+partHTML(parts,c.text)+'</div>'}
function rowHTML(row){const heading=row.before?.kind==='heading'||row.after?.kind==='heading';return '<tr id="row-'+esc(row.id)+'" class="row-'+esc(row.status)+(heading?' row-heading':'')+'"><td>'+cellHTML(row.before,row.beforeParts,'before',row)+'</td><td>'+cellHTML(row.after,row.afterParts,'after',row)+'</td><td><span class="status-badge '+esc(row.status)+'">'+esc(statusLabels[row.status]||row.status)+'</span><div class="explanation-text">'+esc(row.explanation||'')+'</div></td></tr>'}
function renderResults(){const a=state.analysis,all=rows();$('#export-table').disabled=!a||state.busy;$('#before-title').textContent=docTitle('before');$('#after-title').textContent=docTitle('after');$('#before-meta').textContent=a?'Исходный текст · '+all.filter(r=>r.before).length+' фрагментов':'';$('#after-meta').textContent=a?'Новая редакция · '+all.filter(r=>r.after).length+' фрагментов':'';$('#comparison-label').textContent=a?(state.label.includes('редакции')?'Положение о внутреннем аудите · редакции 8 → 9':state.label||'Документ 1 → документ 2'):'Документ 1 → документ 2';const stats=a?.comparison?.stats||{};const counts=[['total','пунктов в таблице'],['changed','изменены'],['added','добавлены'],['removed','удалены']];$('#summary').innerHTML=a?counts.map(([key,label])=>'<div class="summary-stat"><b>'+Number(stats[key]||0)+'</b><span>'+label+'</span></div>').join(''):'';$('#all-count').textContent=all.length;$('#changes-count').textContent=all.filter(r=>r.status!=='unchanged').length;$('#coverage').textContent=a?'Все фрагменты обоих документов включены · без сокращения текста':'';$('#engine').textContent=a?'Сравнение выполнено за '+(a.elapsedMs/1000).toLocaleString('ru',{maximumFractionDigits:2})+' с':'';$('#warnings').innerHTML=(a?.warnings||[]).map(w=>'<div class="warning">'+esc(w)+'</div>').join('');renderTable();renderReport()}
function renderTable(){const all=rows(),query=$('#search').value.trim().toLocaleLowerCase('ru'),type=$('#status-filter').value;const selected=all.filter(r=>(state.filter==='all'||r.status!=='unchanged')&&(type==='all'||r.status===type)&&(!query||[r.before?.text,r.after?.text,r.before?.ref,r.after?.ref,r.explanation].join(' ').toLocaleLowerCase('ru').includes(query)));$('#row-count').textContent=state.analysis?'Показано '+selected.length+' из '+all.length+' · порядок документа 1':'Пункты отображаются в исходном порядке';$('#comparison-body').innerHTML=selected.length?selected.map(rowHTML).join(''):'<tr><td colspan="3"><div class="empty"><span>↔</span><h2>'+(state.analysis?'По этому фильтру пунктов нет':'Сравните два документа')+'</h2><p>'+(state.analysis?'Измените запрос или выберите «Все пункты».':'Выберите файлы на вкладке «Документы».')+'</p></div></td></tr>'}
function organizationalSummary(a){
  const stats=a.stats||{};
  const unitLabels={retained:'Найдено в обоих комплектах',created:'Впервые найдено в документе 2',removed:'Не найдено в документе 2'};
  const functionLabels={preserved:'сохранены',modified:'изменены',moved:'перенесены',missing:'соответствие не найдено'};
  const functions='<h3>Функции в документах</h3><p>Выделено функциональных фрагментов: <b>'+Number(stats.beforeFunctions||0)+'</b> в документе 1 и <b>'+Number(stats.afterFunctions||0)+'</b> в документе 2. Сопоставление фрагментов документа 1: '+Object.entries(functionLabels).map(([key,label])=>esc(label)+' — <b>'+Number(stats[key]||0)+'</b>').join('; ')+'.</p>';
  const units=(a.units||[]).map(unit=>{
    const sources=(unit.evidence||[]).map(e=>esc(e.document)+' · п. '+esc(e.ref)+' · '+(e.side==='before'?'документ 1':e.side==='after'?'документ 2':esc(e.side))).join('; ');
    return '<li style="margin-bottom:14px"><b>'+esc(unit.name)+'</b> — '+esc(unitLabels[unit.status]||unit.status)+'<br><small>Закреплений в документе 1: '+Number(unit.before?.length||0)+'; в документе 2: '+Number(unit.after?.length||0)+'.'+(sources?' Источники: '+sources: '')+'</small></li>';
  }).join('');
  return functions+'<h3>Подразделения</h3>'+(units?'<ul style="padding-left:22px">'+units+'</ul>':'<p>Подразделения по предоставленному тексту не определены.</p>')+'<p>Статус описывает наличие в загруженных комплектах и не доказывает юридическое создание или ликвидацию подразделения. Функциональные фрагменты — отдельная аналитическая выборка; полная сравнительная таблица включает весь текст.</p>';
}
function renderReport(){if(!state.analysis){$('#report-preview').innerHTML='<div class="empty"><h2>Сначала сравните документы</h2><p>Здесь появятся итоги и замечания с источниками.</p></div>';return}const a=state.analysis,stats=a.comparison.stats;$('#report-preview').innerHTML='<div class="eyebrow">VERSA / РЕЗУЛЬТАТ СРАВНЕНИЯ</div><h2>Изменения между редакциями</h2><p><strong>Документ 1:</strong> '+esc(docTitle('before'))+'</p><p><strong>Документ 2:</strong> '+esc(docTitle('after'))+'</p><div class="report-metrics">'+Object.entries(statusLabels).map(([k,v])=>'<span>'+esc(v)+': <b>'+Number(stats[k]||0)+'</b></span>').join('')+'</div><p>Все '+rows().length+' строк включены в выгружаемую таблицу. Слева — исходный текст, в центре — новая редакция, справа — пояснение. Выделение сохраняется при экспорте HTML.</p>'+organizationalSummary(a)+'<h3>Замечания по функциям и ответственности</h3><p>Дополнительная проверка по правилам анализа. Нажмите замечание, чтобы проверить источник и принять решение.</p>'+(a.findings||[]).map(f=>'<button class="finding-button" data-finding="'+esc(f.id)+'"><strong>'+esc(f.title)+'</strong><small>'+esc(riskLabels[f.type]||f.type)+' · '+esc(riskLabels[state.decisions[f.id]||'pending'])+' · '+esc((f.evidence||[]).map(e=>'п. '+e.ref).join(' ↔ '))+'</small></button>').join('')+'<h3>Метод и границы вывода</h3><p>Таблица показывает текстовые изменения. Смысловые соответствия и рекомендации требуют проверки. '+(a.engine?.llmUsed?'Локальная модель участвовала в дополнительном анализе функций.':'В этом запуске языковая модель не использовалась.')+' Документы рассматриваются как данные; инструкции внутри них не исполняются.</p>'}
function openFinding(f){$('#finding-content').innerHTML='<span class="status-badge changed">'+esc(riskLabels[f.type]||f.type)+'</span><h2 id="finding-title">'+esc(f.title)+'</h2><p>'+esc(f.explanation)+'</p><div class="evidence-grid">'+(f.evidence||[]).map(e=>'<section class="quote-card"><strong>'+esc(e.document)+'</strong><small>Пункт '+esc(e.ref)+' · '+(e.side==='before'?'документ 1':'документ 2')+'</small><blockquote>'+esc(e.text)+'</blockquote></section>').join('')+'</div><p><b>Рекомендация:</b> '+esc(f.recommendation)+'</p><textarea id="review-note" class="review-note" aria-label="Комментарий эксперта" placeholder="Комментарий эксперта">'+esc(state.notes[f.id]||'')+'</textarea><div class="review-actions"><span>'+esc(riskLabels[state.decisions[f.id]||'pending'])+'</span><button class="button secondary" data-decision="pending" data-id="'+esc(f.id)+'">Позже</button><button class="button secondary" data-decision="rejected" data-id="'+esc(f.id)+'">Отклонить</button><button class="button primary" data-decision="confirmed" data-id="'+esc(f.id)+'">Подтвердить</button></div>';$('#finding-dialog').showModal()}
const exportStyle='body{margin:35px;font:16px/1.8 Arial,sans-serif;color:#203846}h1{color:#007bb5;font-size:32px}p{color:#67808f}table{border-collapse:collapse;table-layout:fixed;width:100%}th{background:#eaf5fc;color:#13658e;text-align:left;padding:20px;border:1px solid #cee2ef;vertical-align:top;font-size:18px}td{border:1px solid #dce8ef;padding:22px;vertical-align:top;overflow-wrap:anywhere}th:nth-child(1),th:nth-child(2){width:37%}th:last-child{width:26%}.doc-text{white-space:pre-wrap;line-height:1.9}.doc-text del{color:#be3546;font-weight:700;background:#fff0f2;text-decoration:line-through}.doc-text ins{color:#ae2f32;font-weight:700;background:#fff0e9;text-decoration:none}.clause-top{margin-bottom:13px}.clause-ref{font-size:13px;color:#0781bb;background:#edf6fc;padding:4px 7px;border-radius:4px;font-weight:700}.diff-ref{color:#be3546;background:#fff0f2}.source-label{display:block;font-size:12px;color:#7f93a1}.status-badge{display:inline-block;font-size:12px;font-weight:700;color:#0781bb;background:#edf6fc;padding:4px 7px;margin-bottom:12px}.explanation-text{font-size:15px;white-space:pre-line;color:#567286}.absence{color:#98aab6;font-size:14px}.row-heading td{background:#f2f8fc}.row-heading .doc-text{font-weight:700;color:#126992}@page{size:A3 landscape;margin:13mm}@media print{body{margin:0}thead{display:table-header-group}tr{break-inside:avoid}}';
function tableReport(){const a=state.analysis;return '<!doctype html><html lang="ru"><meta charset="utf-8"><title>Versa — сравнительная таблица</title><style>'+exportStyle+'</style><body><h1>Versa · Сравнительная таблица</h1><p>Дата: '+esc(new Date(a.generatedAt||Date.now()).toLocaleString('ru-RU'))+' · '+rows().length+' строк. Красный зачёркнутый текст — удаление; красный жирный текст — дополнение. Порядок исходного документа сохранён, новые пункты вставлены между соответствующими пунктами.</p><table><thead><tr><th>Документ 1<br>'+esc(docTitle('before'))+'</th><th>Документ 2<br>'+esc(docTitle('after'))+'</th><th>Что изменилось</th></tr></thead><tbody>'+rows().map(rowHTML).join('')+'</tbody></table><p>Пояснения носят рекомендательный характер. Выводы ограничены предоставленными документами.</p></body></html>'}
function fullReport(){
  const a=state.analysis;
  const reportStyle='h2{color:#087caf;margin-top:38px}.finding{border:1px solid #dce8ef;border-radius:10px;padding:24px;margin:20px 0;break-inside:avoid}.finding h3{margin:0 0 10px;color:#235e7a}.finding blockquote{white-space:pre-wrap;border-left:3px solid #20a2de;margin:12px 0;padding:12px 18px;background:#f3faff}.finding p,.report-note{white-space:pre-wrap}.source-heading{color:#16698d;font-weight:700}.report-warning{color:#9a5900}';
  const findings=(a.findings||[]).map(f=>{
    const decision=state.decisions[f.id]||'pending';
    const evidence=(f.evidence||[]).map(e=>'<section><div class="source-heading">'+esc(e.document)+' · пункт '+esc(e.ref)+' · '+(e.side==='before'?'Документ 1':e.side==='after'?'Документ 2':esc(e.side))+'</div><blockquote>'+esc(e.text)+'</blockquote></section>').join('');
    return '<article class="finding"><h3>'+esc(f.title)+'</h3><p><b>Тип:</b> '+esc(riskLabels[f.type]||f.type)+'<br><b>Статус проверки:</b> '+esc(riskLabels[decision]||decision)+'</p><p>'+esc(f.explanation)+'</p>'+evidence+'<p><b>Рекомендация:</b> '+esc(f.recommendation)+'</p><p><b>Комментарий эксперта:</b> '+esc(state.notes[f.id]||'Не добавлен')+'</p></article>';
  }).join('');
  const methods='<h2>Метод и границы вывода</h2><p>Таблица отражает текстовые различия предоставленных документов. Сопоставление пунктов и замечания по функциям требуют экспертной проверки. Отсутствие функции в загруженном комплекте не доказывает её фактическую утрату. Экспертные статусы и комментарии сохранены на момент выгрузки.</p><p>'+(a.engine?.llmUsed?'Локальная языковая модель участвовала в дополнительном анализе функций.':'В этом запуске языковая модель не использовалась. Сравнение выполнено автономным алгоритмом.')+' Источники и цитаты взяты из загруженного текста; инструкции внутри документов не исполняются. Внешняя нормативная проверка и промышленная оценка точности не проводились.</p>';
  const warnings=(a.warnings||[]).length?'<h2>Ограничения входных данных</h2><ul>'+a.warnings.map(w=>'<li class="report-warning">'+esc(w)+'</li>').join('')+'</ul>':'';
  const appendix=organizationalSummary(a)+'<h2>Замечания по функциям и ответственности</h2>'+(findings||'<p>Замечания по правилам анализа не выявлены. Это не заменяет экспертную проверку.</p>')+methods+warnings;
  return tableReport().replace('<title>Versa — сравнительная таблица</title>','<title>Versa — заключение и сравнительная таблица</title>').replace('<h1>Versa · Сравнительная таблица</h1>','<h1>Versa · Заключение и сравнительная таблица</h1>').replace('</style>',reportStyle+'</style>').replace('</body>',appendix+'</body>');
}
function exportConclusion(){if(state.analysis)download(fullReport(),'html')}
async function download(content,extension){if(!state.analysis)return;try{const result=await api('/api/export',{content,extension});const link=document.createElement('a');link.href=result.href;link.download='Versa-сравнение.'+extension;document.body.appendChild(link);link.click();link.remove();message('Файл сохранён: '+result.path)}catch(e){message(e.message,true)}}
function exportHTML(){if(state.analysis)download(tableReport(),'html')}
function exportCSV(){if(!state.analysis)return;const cell=v=>{let s=String(v??'');if(/^(\s*[=+@-]|[\t\r])/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const result=[[docTitle('before'),docTitle('after'),'Что изменилось']];const clause=(value,side)=>value?((names(side).length>1?(value.document||'')+'\n':'')+(value.ref||'')+'\n'+value.text):'Данный пункт в документе отсутствует.';for(const r of rows())result.push([clause(r.before,'before'),clause(r.after,'after'),(statusLabels[r.status]||r.status)+'. '+r.explanation]);download('\ufeff'+result.map(r=>r.map(cell).join(';')).join('\r\n'),'csv')}
document.addEventListener('click',event=>{const view=event.target.closest('[data-view]');if(view)setView(view.dataset.view);const filter=event.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;$$('[data-filter]').forEach(el=>el.classList.toggle('active',el===filter));renderTable();$('.comparison-scroll').scrollTop=0}const remove=event.target.closest('[data-remove-side]');if(remove&&!state.busy){state[remove.dataset.removeSide].splice(Number(remove.dataset.index),1);invalidate();renderFiles()}const item=event.target.closest('[data-finding]');if(item){const finding=state.analysis?.findings.find(f=>f.id===item.dataset.finding);if(finding)openFinding(finding)}const decision=event.target.closest('[data-decision]');if(decision){state.decisions[decision.dataset.id]=decision.dataset.decision;state.notes[decision.dataset.id]=$('#review-note').value;$('#finding-dialog').close();renderReport()}});
document.addEventListener('input',event=>{if(event.target.dataset.nameSide){state[event.target.dataset.nameSide][Number(event.target.dataset.index)].name=event.target.value;invalidate()}if(event.target.dataset.ownerSide){state[event.target.dataset.ownerSide][Number(event.target.dataset.index)].unit=event.target.value;invalidate()}});
$('#new-comparison').onclick=()=>setView('documents');$('#load-demo').onclick=()=>loadDemo();$('#run-analysis').onclick=analyze;$('#search').oninput=renderTable;$('#status-filter').onchange=renderTable;$('#export-table').onclick=exportHTML;$('#export-html').onclick=exportConclusion;$('#export-csv').onclick=exportCSV;$('#export-json').onclick=()=>state.analysis&&download(JSON.stringify({...state.analysis,expertDecisions:state.decisions,expertNotes:state.notes},null,2),'json');$('#to-top').onclick=()=>$('.comparison-scroll').scrollTo({top:0,behavior:'smooth'});$('#close-dialog').onclick=()=>$('#finding-dialog').close();$('#finding-dialog').onclick=e=>{if(e.target===$('#finding-dialog'))$('#finding-dialog').close()};
for(const side of ['before','after']){$('#files-'+side).onchange=e=>readFiles(side,e.target.files);const zone=$('#drop-'+side);zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag')};zone.ondragleave=()=>zone.classList.remove('drag');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag');readFiles(side,e.dataTransfer.files)}}
(async()=>{try{state.health=await api('/api/health');$('#use-llm').disabled=!state.health.llmConfigured;$('#llm-help').textContent=state.health.llmConfigured?'Доступна модель '+state.health.llmModel:'Сравнительная таблица работает без модели и API-ключа.';await loadDemo(true)}catch(e){message(e.message,true);setView('documents')}})();


function setTableExpanded(expanded){document.body.classList.toggle('table-expanded',expanded);$('#expand-table').textContent=expanded?'↙ Свернуть':'⤢ На весь экран';$('#expand-table').setAttribute('aria-pressed',String(expanded));}
function openExport(){if(!state.analysis||state.busy)return;$('#download-count').textContent='Все '+rows().length+' строк с названиями документов, выделением изменений и пояснениями.';$('#download-dialog').showModal();}
function saveLink(result,extension){const link=document.createElement('a');link.href=result.href;link.download='Versa-сравнение.'+extension;document.body.appendChild(link);link.click();link.remove();}
async function exportBinary(extension){
  if(!state.analysis||state.busy||state.exportBusy)return;
  state.exportBusy=true;$$('[data-export-format]').forEach(b=>b.disabled=true);
  $('#export-progress').textContent='Готовим '+extension.toUpperCase()+'…';message('Готовим '+extension.toUpperCase()+' со всеми пунктами…',false,true);
  try{const result=await api('/api/export-document',{extension,analysis:{comparison:state.analysis.comparison}});saveLink(result,extension);message('Файл сохранён: '+result.path);$('#export-progress').textContent=extension.toUpperCase()+' сохранён';}
  catch(e){message(e.message,true);$('#export-progress').textContent=e.message;}
  finally{state.exportBusy=false;$$('[data-export-format]').forEach(b=>b.disabled=false);}
}
$('#export-table').onclick=openExport;$('#table-download').onclick=openExport;
$('#expand-table').onclick=()=>setTableExpanded(!document.body.classList.contains('table-expanded'));
$('#close-download').onclick=()=>$('#download-dialog').close();
$('#download-dialog').onclick=e=>{if(e.target===$('#download-dialog'))$('#download-dialog').close();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#download-dialog').open&&!$('#finding-dialog').open)setTableExpanded(false);});
document.addEventListener('click',e=>{const b=e.target.closest('[data-export-format]');if(!b)return;const format=b.dataset.exportFormat;$('#download-dialog').close();if(['docx','xlsx','pdf'].includes(format))exportBinary(format);else if(format==='html')exportHTML();else if(format==='csv')exportCSV();else if(format==='json'&&state.analysis)download(JSON.stringify({...state.analysis,expertDecisions:state.decisions,expertNotes:state.notes},null,2),'json');});
